apiVersion: 1

datasources:
  - name: Neo4j
    type: kniepdennis-neo4j-datasource
    jsonData:
      url: "bolt://neo4j:7687"
      database: ${NEO4J_DB:-neo4j}
      username: ${NEO4J_USER:-neo4j}
    secureJsonData:
      password: ${NEO4J_PASSWORD:-password}
    editable: true

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: ${POSTGRES_DB:-grafana}
    user: ${POSTGRES_USER:-grafana}
    secureJsonData:
      password: ${POSTGRES_PASSWORD:-grafana}
    jsonData:
      sslmode: disable
    isDefault: true
